apiVersion: extensions/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: in4it/node-demo-app:latest
        ports:
        - name: demo-app-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: demo-app-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: demo-app
  type: NodePort
